#!/usr/bin/env python3
"""Export a reproducibility-critical runtime/model environment record.

This script is intentionally read-only. It collects local software, GPU, Ollama,
and model metadata needed to reproduce local open-weight LLM runs. Run it on the
same host used for final experiments and commit/archive the resulting Markdown
file with the release artifacts.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import importlib.metadata as importlib_metadata
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

DEFAULT_MODELS = [
    "qwen2.5:14b",
    "qwen3:14b",
    "gemma3:12b",
    "llama3.1:8b",
    "mistral-small3.1:24b",
]

DEFAULT_PACKAGES = [
    "python",
    "torch",
    "transformers",
    "sentence-transformers",
    "pandas",
    "numpy",
    "scipy",
    "scikit-learn",
    "pyyaml",
    "tqdm",
]


def run_cmd(cmd: list[str], timeout: int = 45) -> dict[str, object]:
    if shutil.which(cmd[0]) is None:
        return {"available": False, "cmd": cmd, "returncode": None, "stdout": "", "stderr": f"{cmd[0]} not found"}
    try:
        p = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
        return {
            "available": True,
            "cmd": cmd,
            "returncode": p.returncode,
            "stdout": p.stdout.strip(),
            "stderr": p.stderr.strip(),
        }
    except Exception as exc:  # pragma: no cover - diagnostic script
        return {"available": True, "cmd": cmd, "returncode": None, "stdout": "", "stderr": repr(exc)}


def package_versions() -> dict[str, str]:
    versions: dict[str, str] = {"python": sys.version.replace("\n", " ")}
    for pkg in DEFAULT_PACKAGES:
        if pkg == "python":
            continue
        try:
            versions[pkg] = importlib_metadata.version(pkg)
        except importlib_metadata.PackageNotFoundError:
            versions[pkg] = "not installed"
    return versions


def torch_cuda_summary() -> dict[str, object]:
    try:
        import torch  # type: ignore

        available = bool(torch.cuda.is_available())
        devices = []
        if available:
            for i in range(torch.cuda.device_count()):
                props = torch.cuda.get_device_properties(i)
                devices.append({
                    "index": i,
                    "name": torch.cuda.get_device_name(i),
                    "total_memory_bytes": int(props.total_memory),
                    "total_memory_gb": round(props.total_memory / (1024**3), 2),
                    "major": int(props.major),
                    "minor": int(props.minor),
                })
        return {"torch_importable": True, "cuda_available": available, "devices": devices}
    except Exception as exc:  # pragma: no cover
        return {"torch_importable": False, "error": repr(exc), "cuda_available": False, "devices": []}


def collect(models: list[str]) -> dict[str, object]:
    data: dict[str, object] = {
        "generated_at_utc": _dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "platform": {
            "platform": platform.platform(),
            "python_executable": sys.executable,
            "cwd": os.getcwd(),
        },
        "package_versions": package_versions(),
        "torch_cuda": torch_cuda_summary(),
        "nvidia_smi": run_cmd(["nvidia-smi", "--query-gpu=name,memory.total,driver_version,cuda_version", "--format=csv,noheader"], timeout=30),
        "nvidia_smi_full": run_cmd(["nvidia-smi"], timeout=30),
        "ollama_version": run_cmd(["ollama", "--version"], timeout=30),
        "ollama_list": run_cmd(["ollama", "list"], timeout=30),
        "ollama_models": {},
        "deterministic_inference_controls": {
            "temperature": 0,
            "max_generation_tokens": 1024,
            "context_window_tokens": 32768,
            "qwen3_thinking_disabled": True,
            "recommended_ollama_num_parallel": 1,
        },
    }
    model_records: dict[str, object] = {}
    for model in models:
        # --verbose is supported by recent Ollama versions and exposes model metadata when available.
        verbose = run_cmd(["ollama", "show", model, "--verbose"], timeout=60)
        plain = run_cmd(["ollama", "show", model], timeout=60)
        model_records[model] = {"show_verbose": verbose, "show": plain}
    data["ollama_models"] = model_records
    return data


def write_markdown(data: dict[str, object], path: Path) -> None:
    lines: list[str] = []
    lines.append("# Runtime Reproducibility Record")
    lines.append("")
    lines.append("This record is generated by `scripts/export_runtime_record.py` on the host used for local LLM inference. It is intended to preserve exact runtime and model metadata for JAIR reproducibility review.")
    lines.append("")
    lines.append(f"Generated at UTC: `{data['generated_at_utc']}`")
    lines.append("")
    lines.append("## Deterministic inference controls")
    lines.append("")
    controls = data.get("deterministic_inference_controls", {})
    for k, v in controls.items():
        lines.append(f"- `{k}`: `{v}`")
    lines.append("")
    lines.append("## Platform")
    lines.append("")
    for k, v in data.get("platform", {}).items():
        lines.append(f"- `{k}`: `{v}`")
    lines.append("")
    lines.append("## Package versions")
    lines.append("")
    for k, v in data.get("package_versions", {}).items():
        lines.append(f"- `{k}`: `{v}`")
    lines.append("")
    lines.append("## CUDA / GPU")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(data.get("torch_cuda", {}), indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### nvidia-smi query")
    lines.append("")
    lines.append("```text")
    lines.append(str(data.get("nvidia_smi", {}).get("stdout", "")))
    stderr = str(data.get("nvidia_smi", {}).get("stderr", ""))
    if stderr:
        lines.append("\n[stderr]\n" + stderr)
    lines.append("```")
    lines.append("")
    lines.append("## Ollama")
    lines.append("")
    lines.append("### ollama --version")
    lines.append("```text")
    lines.append(str(data.get("ollama_version", {}).get("stdout", "")))
    stderr = str(data.get("ollama_version", {}).get("stderr", ""))
    if stderr:
        lines.append("\n[stderr]\n" + stderr)
    lines.append("```")
    lines.append("")
    lines.append("### ollama list")
    lines.append("```text")
    lines.append(str(data.get("ollama_list", {}).get("stdout", "")))
    stderr = str(data.get("ollama_list", {}).get("stderr", ""))
    if stderr:
        lines.append("\n[stderr]\n" + stderr)
    lines.append("```")
    lines.append("")
    lines.append("## Model records")
    lines.append("")
    lines.append("Each block preserves the local `ollama show --verbose` and `ollama show` output for the evaluated tag. These outputs should include digest, parameter, and quantization metadata when exposed by the installed Ollama version and local model store.")
    for model, rec in (data.get("ollama_models", {}) or {}).items():
        lines.append("")
        lines.append(f"### {model}")
        lines.append("")
        lines.append("#### ollama show --verbose")
        lines.append("```text")
        lines.append(str(rec.get("show_verbose", {}).get("stdout", "")))
        stderr = str(rec.get("show_verbose", {}).get("stderr", ""))
        if stderr:
            lines.append("\n[stderr]\n" + stderr)
        lines.append("```")
        lines.append("")
        lines.append("#### ollama show")
        lines.append("```text")
        lines.append(str(rec.get("show", {}).get("stdout", "")))
        stderr = str(rec.get("show", {}).get("stderr", ""))
        if stderr:
            lines.append("\n[stderr]\n" + stderr)
        lines.append("```")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="RUNTIME_REPRODUCIBILITY_RECORD.md", help="Markdown output path")
    parser.add_argument("--json-output", default="", help="Optional JSON output path")
    parser.add_argument("--models", nargs="*", default=DEFAULT_MODELS, help="Ollama model tags to inspect")
    args = parser.parse_args()

    data = collect(args.models)
    write_markdown(data, Path(args.output))
    if args.json_output:
        Path(args.json_output).write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {args.output}")
    if args.json_output:
        print(f"Wrote {args.json_output}")


if __name__ == "__main__":
    main()
